### ISSUE TITLE
Deploy failure: pg_ext.so shared object file not found

### ISSUE THREAD

**Issue by kendocode** [tongueroo/jets#104]
- Created VPC and Postgresql RDS instance following [standard AWS procedure](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_GettingStarted.CreatingConnecting.PostgreSQL.html).
- Verified public accessibility by making  connection to DB via pgAdmin and psql
- Created new jets repo on local machine with `jets new demo`.
- Removed `mysql2` gem and replaced with `pg 0.21`; executed `bundle install`
- Executed  `jets g scaffold Post title body published:boolean` with success
- Executed `jets db:create db:migrate` with success
- Verified correct functioning of PostsController on localhost:8888 by performing CRUD operations on posts
- Verified Jets connection to RDS instance by executing `JETS_REMOTE_ENV=1 jets db:create db:migrate` with success
- Executed `jets deploy` with apparent success; received API endpoint.
- Attempted to visit endpoint, received error message `{"message": "Internal server error"}`
- Testing Lambda posts_controller-index function yields: 
`{
  "errorMessage": "libpq.so.5: cannot open shared object file: No such file or directory - /opt/ruby/gems/2.5.0/gems/pg-0.21.0/lib/pg_ext.so",
  "errorType": "Init<LoadError>",
  "stackTrace": [
    "/opt/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'",
    "/opt/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'",
    "/opt/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'",
    "/opt/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'",
    "/opt/ruby/gems/2.5.0/gems/pg-0.21.0/lib/pg.rb:4:in `<top (required)>'",
    "/opt/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'",
    "/opt/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'",
    "/opt/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'",
    "/opt/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'",
    "/opt/ruby/gems/2.5.0/gems/jets-1.3.8/lib/jets/db.rb:9:in `<top (required)>'",
    "/opt/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'",
    "/opt/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'",
    "/opt/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'",
    "/opt/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'",
    "/opt/ruby/gems/2.5.0/gems/jets-1.3.8/lib/jets.rb:70:in `<top (required)>'",
    "/var/task/handlers/controllers/posts_controller.rb:2:in `require'",
    "/var/task/handlers/controllers/posts_controller.rb:2:in `<top (required)>'",
    "/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
    "/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'"
  ]
}`

I've run through several iterations of this process with identical results over the past couple of days. I attempted a deploy using MySQL and was able to connect to the Jets splash screen at the API endpoint. When I have time I will also try DynamoDB, just to test. But I am much more familiar with Postgres and would really prefer to use it. But I can't seem to make it work, and I'm not smart enough to figure out why.

I'm guessing that something is going wrong with the process of injecting the pg version compiled with AMI native extensions but don't understand that process well enough to test further.

System notes:
- OS: Pop!OS 18.04
- version manager: asdf  (ruby, node, and postgres)
- ports: I run postgres 9.6 and 10.4 under asdf locally on port 5555, to avoid conflicts with dev setup from work that binds 5432 to a docker container. I don't think that's causing trouble because by specifying the port I'm able to connect successfully to both the local db on 5555 and the RDS instance on 5432, but offer it just in case.

That's all I can think of that might help. If you give me directions for things to try I'm perfectly willing to test anything. I am excited about the concept, like the implementation, and have a perfect use case for Jets. I want to put it in production, and would already be staging it if not for this hiccup.

Thanks for the tools. If there's anything within my ability, or even within a reasonable stretch, I'd like to contribute at some point.

**Comment by tongueroo** [comment]
@kendocode Dug into this. Had to rebuild the pg 0.21 version. When Jets updated to official Ruby, only the latest pg version had been rebuilt.

Jets caches downloaded gems in `/tmp/jets` so do this:

    rm -rf /tmp/jets # blow away full cache
    jets deploy

Thanks for reporting.  Just tested it with pg 0.21 version, should work now! 👍

**Comment by panbanda** [comment]
@tongueroo Hey there.  I just upgrade to 3.0.0 and have my pg gem.  I did remove the /tmp/jets but still getting this error.  

```
libldap_r-2.4.so.2: cannot open shared object file: No such file or directory - /opt/ruby/gems/2.7.0/gems/pg-1.2.3/lib/pg_ext.so
```

I believe it's cause its running on a slimmer version of amazon linux.  

https://northsail.io/articles/aws-lambda-ruby-2-7-pg-gem-libldap-error

Do you have any thoughts on how to work around this?  Would this be a fix in the serverlessgems?

**Comment by tongueroo** [comment]
@panbanda Thanks for the report. There this specific gem on serverlessgems. Fixed now. Try again

    rm -rf /tmp/jets
    jets deploy

**Comment by hkrdrm** [comment]
Hi @tongueroo I've run into this problem as well and removing the /tmp/jets directory isn't working.

**Comment by tongueroo** [comment]
For posterity. Followed up on this for @hkrdrm 

Here's the followup.

Unsure what's going on with postgresql for you. Dug into it a bit:

1. Create jets demo app: https://github.com/tongueroo/jets-postgresql-demo
2. Create a throwaway RDS PostgreSQL DB
3. Deploy the jets app to Lambda

It seems to work fine. So there's something different about your setup. Maybe try to upgrade the pg gem version to the latest version?

Here's some relevant debugging information:

* https://github.com/tongueroo/jets-postgresql-demo/blob/master/app/controllers/info_controller.rb
* https://av9h8dja6e.execute-api.us-west-2.amazonaws.com/dev/info

It seems like there was another gem that was causing the issue.

**Comment by hkrdrm** [comment]
Thanks again for the help @tongueroo I ended up getting it working today; I had to build the missing .so files with docker and copy them to the lib folder in the repo before deploying.  Not sure why this was needed looks like it should just work out the box.

Dockerfile
```
FROM lambci/lambda:build-ruby2.7

RUN yum install -y postgresql postgresql-devel
RUN gem update bundler

CMD "/bin/bash"
```

makefile
```
image:
	docker build -t lambci/lambda:build-ruby2.7 .
install:
	make image
	docker run --rm -it -v $$PWD:/var/task -w /var/task lambci/lambda:build-ruby2.7 make _install
_install:
	bundle config --local silence_root_warning true
	bundle install --path vendor/bundle --clean
	mkdir -p /var/task/lib
	cp -a /usr/lib64/libpq.so.5.5 /var/task/lib/libpq.so.5
	cp -a /usr/lib64/libldap_r-2.4.so.2.10.7 /var/task/lib/libldap_r-2.4.so.2
	cp -a /usr/lib64/liblber-2.4.so.2.10.7 /var/task/lib/liblber-2.4.so.2
	cp -a /usr/lib64/libsasl2.so.3.0.0 /var/task/lib/libsasl2.so.3
	cp -a /usr/lib64/libssl3.so /var/task/lib/
	cp -a /usr/lib64/libsmime3.so /var/task/lib/
	cp -a /usr/lib64/libnss3.so /var/task/lib/
	cp -a /usr/lib64/libnssutil3.so /var/task/lib/
```

```
make
make install
jets deploy
```

**Comment by tongueroo** [comment]
@hkrdrm Interesting. Thanks for following up. Still unsure exactly why it errors for your project, and you had to build it yourself. But updated the build serverlessgems build process for pg gem. Made some improvements and included the additional shared libs that you have above - most were already included. Unsure, but rebuilt all pg gems and tested the latest manually again. FWIW, the serverless builder process has a health check that runs at the end. For pg, it connects to a postgresql db inside a fresh docker container with the extracted gem source and executes a simple "select 1" query. 

Thinking maybe your project is executing certain queries, and the pg loads some shared libraries lazily for specific queries. That's a possible explanation. Unsure. If you have time, maybe `rm /tmp/jets` again and try deploying with the serverless pg gem version. If you figured it out, let me know. No sweat either way, though, leaving this closed. This report was helpful. Thanks.

**Comment by hkrdrm** [comment]
Yeah that got it works with having to build it now thanks.
