### ISSUE TITLE
Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)

### ISSUE THREAD

**Issue by hamza-sondermarketing** [tongueroo/jets#463]
## Checklist

- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [ ] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |     Linux Ubuntu 18.04    |
| Jets             |    2.3.15     |
| Ruby             |     2.5.3    |

---

## Expected Behaviour

After deployment of Rails application using After Burner, The Endpoint URL should work.

## Current Behavior

After hitting the Endpoint URl, it returns the timeout error. Logs message says:
`Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)`
Even I moved the Uglifier and coffee-rails gem to development but still getting the same error. 
``

## Step-by-step reproduction instructions
`jets deploy production`
ENDPOINT URL: `https://2yne7fyus8.execute-api.us-east-1.amazonaws.com/prod/`

## Solution Suggestion
Maybe some thing is missing here.

**Comment by matheusvetor** [comment]
Show here your Gemfile

**Comment by hamza-sondermarketing** [comment]
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.3'

gem 'rails', '~> 5.2.4', '>= 5.2.4.2'

gem 'pg', '>= 0.18', '< 2.0'

gem 'puma', '~> 3.11'

gem 'sass-rails', '~> 5.0'



gem 'turbolinks', '~> 5'

gem 'jbuilder', '~> 2.5'

gem 'bootsnap', '>= 1.1.0', require: false

gem 'jquery-rails'

gem 'bootstrap', '~> 4.4.1'

gem 'devise'

gem "rolify"

group :development, :test do

  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do

  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'

  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'uglifier', '>= 1.3.0'
  gem 'coffee-rails', '~> 4.2'
  gem "letter_opener"
end

group :test do

  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'

  gem 'chromedriver-helper'
end


gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

**Comment by matheusvetor** [comment]
In Rails when we dont have nodejs we need to put some v8 javascript library.

As said on error you will need to choose some library, available on [rails/execjs](https://github.com/rails/execjs)

I used to choose [therubyracer](https://github.com/rubyjs/therubyracer) because its the easier choice.

**Comment by matheusvetor** [comment]
@tongueroo has a [code example](https://github.com/tongueroo/jets-example-crud-html/blob/master/Gemfile) serving html. It's uses webpacker, maybe the solution for your case

btw, your gemfile don't uses jets gem. I think this is required to be working.

**Comment by hamza-sondermarketing** [comment]
@matheusvetor I tried adding `gem 'mini_racer', platforms: :ruby` gem, as RubyRacer is not supported by rails anymore I guess.
Adding mini_racer gem still giving me same error

**Comment by matheusvetor** [comment]
You already tried to use your gemfile like [code example](https://github.com/tongueroo/jets-example-crud-html/blob/master/Gemfile) Tongueroo's repo

**Comment by hamza-sondermarketing** [comment]
@matheusvetor The gemfile you shared is for the jets application. But I am using After burner for rails and I have Rails Gemfile which I have shared. I have added `gem "jets-rails"`  gem into my Gemfile though.

**Comment by matheusvetor** [comment]
Like #314. The problem should solved by moving uglifier and coffee-rails to development environment on Gemfile.  Btw, your Gemfile has some gems who needs a javascript runtime like jquery, sass, bootstrap.

**Comment by matheusvetor** [comment]
Look [this documentation](https://rubyonjets.com/docs/rails/afterburner/)

**Comment by hamza-sondermarketing** [comment]
@matheusvetor I have used `webpacker` gem and include the javascript libraries and seems like I am not getting the error related to Javascript runtime any more. 

But now I am getting the following error in cloudwatch and need a suggestion what should I do.

`Could not load database configuration. No such file - ["config/database.yml"]`

What should I do for the database in AWS lambda ?

**Comment by hamza-sondermarketing** [comment]
I have manage to use webrick instead and now all errors are removed from the cloudwatch but still getting the message below when hit this URL: `https://r0rbp5mrbc.execute-api.us-east-1.amazonaws.com/dev/`

`{`
`message: "Endpoint request timed out"`
`}`

Please see the cloudwatch logs below: 

![cloudwatch](https://user-images.githubusercontent.com/61772563/78021267-56508080-736c-11ea-9dbf-a976e6671f09.png)

@matheusvetor  Can you help me here ?

**Comment by matheusvetor** [comment]
can you provide again your gemfile and gemfile.lock?

**Comment by hamza-sondermarketing** [comment]
@matheusvetor  Please see the below gemfile and gemfile.lock file

**Gemfile**:

> source 'https://rubygems.org'
> git_source(:github) { |repo| "https://github.com/#{repo}.git" }
> 
> ruby '2.5.3'
> 
> 
> gem 'rails', '~> 5.2.4', '>= 5.2.4.2'
> 
> gem 'pg', '>= 0.18', '< 2.0'
> 
> gem 'puma', '~> 3.11'
> 
> gem 'webpacker', '~> 3.5'
> 
> 
> gem 'sass-rails', '~> 5.0'
> 
> 
> gem 'jbuilder', '~> 2.5'
> 
> gem 'bootsnap', '>= 1.1.0', require: false
> 
> gem 'devise'
> 
> gem "rolify"
> 
> group :development, :test do
>   gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
> end
> 
> group :development do
>   gem 'web-console', '>= 3.3.0'
>   gem 'listen', '>= 3.0.5', '< 3.2'
>   gem 'spring'
>   gem 'spring-watcher-listen', '~> 2.0.0'
>   gem "letter_opener"
> end
> 
> group :test do
>   gem 'capybara', '>= 2.15'
>   gem 'selenium-webdriver'
>   gem 'chromedriver-helper'
> end
> 
> gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
> 

**Gemfile.lock**

> GEM
>   remote: https://rubygems.org/
>   specs:
>     actioncable (5.2.4.2)
>       actionpack (= 5.2.4.2)
>       nio4r (~> 2.0)
>       websocket-driver (>= 0.6.1)
>     actionmailer (5.2.4.2)
>       actionpack (= 5.2.4.2)
>       actionview (= 5.2.4.2)
>       activejob (= 5.2.4.2)
>       mail (~> 2.5, >= 2.5.4)
>       rails-dom-testing (~> 2.0)
>     actionpack (5.2.4.2)
>       actionview (= 5.2.4.2)
>       activesupport (= 5.2.4.2)
>       rack (~> 2.0, >= 2.0.8)
>       rack-test (>= 0.6.3)
>       rails-dom-testing (~> 2.0)
>       rails-html-sanitizer (~> 1.0, >= 1.0.2)
>     actionview (5.2.4.2)
>       activesupport (= 5.2.4.2)
>       builder (~> 3.1)
>       erubi (~> 1.4)
>       rails-dom-testing (~> 2.0)
>       rails-html-sanitizer (~> 1.0, >= 1.0.3)
>     activejob (5.2.4.2)
>       activesupport (= 5.2.4.2)
>       globalid (>= 0.3.6)
>     activemodel (5.2.4.2)
>       activesupport (= 5.2.4.2)
>     activerecord (5.2.4.2)
>       activemodel (= 5.2.4.2)
>       activesupport (= 5.2.4.2)
>       arel (>= 9.0)
>     activestorage (5.2.4.2)
>       actionpack (= 5.2.4.2)
>       activerecord (= 5.2.4.2)
>       marcel (~> 0.3.1)
>     activesupport (5.2.4.2)
>       concurrent-ruby (~> 1.0, >= 1.0.2)
>       i18n (>= 0.7, < 2)
>       minitest (~> 5.1)
>       tzinfo (~> 1.1)
>     addressable (2.7.0)
>       public_suffix (>= 2.0.2, < 5.0)
>     archive-zip (0.12.0)
>       io-like (~> 0.3.0)
>     arel (9.0.0)
>     bcrypt (3.1.13)
>     bindex (0.8.1)
>     bootsnap (1.4.6)
>       msgpack (~> 1.0)
>     builder (3.2.4)
>     byebug (11.1.1)
>     capybara (3.31.0)
>       addressable
>       mini_mime (>= 0.1.3)
>       nokogiri (~> 1.8)
>       rack (>= 1.6.0)
>       rack-test (>= 0.6.3)
>       regexp_parser (~> 1.5)
>       xpath (~> 3.2)
>     childprocess (3.0.0)
>     chromedriver-helper (2.1.1)
>       archive-zip (~> 0.10)
>       nokogiri (~> 1.8)
>     concurrent-ruby (1.1.6)
>     crass (1.0.6)
>     devise (4.7.1)
>       bcrypt (~> 3.0)
>       orm_adapter (~> 0.1)
>       railties (>= 4.1.0)
>       responders
>       warden (~> 1.2.3)
>     erubi (1.9.0)
>     ffi (1.12.2)
>     globalid (0.4.2)
>       activesupport (>= 4.2.0)
>     i18n (1.8.2)
>       concurrent-ruby (~> 1.0)
>     io-like (0.3.1)
>     jbuilder (2.10.0)
>       activesupport (>= 5.0.0)
>     launchy (2.5.0)
>       addressable (~> 2.7)
>     letter_opener (1.7.0)
>       launchy (~> 2.2)
>     listen (3.1.5)
>       rb-fsevent (~> 0.9, >= 0.9.4)
>       rb-inotify (~> 0.9, >= 0.9.7)
>       ruby_dep (~> 1.2)
>     loofah (2.4.0)
>       crass (~> 1.0.2)
>       nokogiri (>= 1.5.9)
>     mail (2.7.1)
>       mini_mime (>= 0.1.1)
>     marcel (0.3.3)
>       mimemagic (~> 0.3.2)
>     method_source (1.0.0)
>     mimemagic (0.3.4)
>     mini_mime (1.0.2)
>     mini_portile2 (2.4.0)
>     minitest (5.14.0)
>     msgpack (1.3.3)
>     nio4r (2.5.2)
>     nokogiri (1.10.9)
>       mini_portile2 (~> 2.4.0)
>     orm_adapter (0.5.0)
>     pg (1.2.3)
>     public_suffix (4.0.3)
>     puma (3.12.4)
>     rack (2.2.2)
>     rack-proxy (0.6.5)
>       rack
>     rack-test (1.1.0)
>       rack (>= 1.0, < 3)
>     rails (5.2.4.2)
>       actioncable (= 5.2.4.2)
>       actionmailer (= 5.2.4.2)
>       actionpack (= 5.2.4.2)
>       actionview (= 5.2.4.2)
>       activejob (= 5.2.4.2)
>       activemodel (= 5.2.4.2)
>       activerecord (= 5.2.4.2)
>       activestorage (= 5.2.4.2)
>       activesupport (= 5.2.4.2)
>       bundler (>= 1.3.0)
>       railties (= 5.2.4.2)
>       sprockets-rails (>= 2.0.0)
>     rails-dom-testing (2.0.3)
>       activesupport (>= 4.2.0)
>       nokogiri (>= 1.6)
>     rails-html-sanitizer (1.3.0)
>       loofah (~> 2.3)
>     railties (5.2.4.2)
>       actionpack (= 5.2.4.2)
>       activesupport (= 5.2.4.2)
>       method_source
>       rake (>= 0.8.7)
>       thor (>= 0.19.0, < 2.0)
>     rake (13.0.1)
>     rb-fsevent (0.10.3)
>     rb-inotify (0.10.1)
>       ffi (~> 1.0)
>     regexp_parser (1.7.0)
>     responders (3.0.0)
>       actionpack (>= 5.0)
>       railties (>= 5.0)
>     rolify (5.2.0)
>     ruby_dep (1.5.0)
>     rubyzip (2.3.0)
>     sass (3.7.4)
>       sass-listen (~> 4.0.0)
>     sass-listen (4.0.0)
>       rb-fsevent (~> 0.9, >= 0.9.4)
>       rb-inotify (~> 0.9, >= 0.9.7)
>     sass-rails (5.1.0)
>       railties (>= 5.2.0)
>       sass (~> 3.1)
>       sprockets (>= 2.8, < 4.0)
>       sprockets-rails (>= 2.0, < 4.0)
>       tilt (>= 1.1, < 3)
>     selenium-webdriver (3.142.7)
>       childprocess (>= 0.5, < 4.0)
>       rubyzip (>= 1.2.2)
>     spring (2.1.0)
>     spring-watcher-listen (2.0.1)
>       listen (>= 2.7, < 4.0)
>       spring (>= 1.2, < 3.0)
>     sprockets (3.7.2)
>       concurrent-ruby (~> 1.0)
>       rack (> 1, < 3)
>     sprockets-rails (3.2.1)
>       actionpack (>= 4.0)
>       activesupport (>= 4.0)
>       sprockets (>= 3.0.0)
>     thor (1.0.1)
>     thread_safe (0.3.6)
>     tilt (2.0.10)
>     tzinfo (1.2.6)
>       thread_safe (~> 0.1)
>     warden (1.2.8)
>       rack (>= 2.0.6)
>     web-console (3.7.0)
>       actionview (>= 5.0)
>       activemodel (>= 5.0)
>       bindex (>= 0.4.0)
>       railties (>= 5.0)
>     webpacker (3.6.0)
>       activesupport (>= 4.2)
>       rack-proxy (>= 0.6.1)
>       railties (>= 4.2)
>     websocket-driver (0.7.1)
>       websocket-extensions (>= 0.1.0)
>     websocket-extensions (0.1.4)
>     xpath (3.2.0)
>       nokogiri (~> 1.8)
> 
> PLATFORMS
>   ruby
> 
> DEPENDENCIES
>   bootsnap (>= 1.1.0)
>   byebug
>   capybara (>= 2.15)
>   chromedriver-helper
>   devise
>   jbuilder (~> 2.5)
>   letter_opener
>   listen (>= 3.0.5, < 3.2)
>   pg (>= 0.18, < 2.0)
>   puma (~> 3.11)
>   rails (~> 5.2.4, >= 5.2.4.2)
>   rolify
>   sass-rails (~> 5.0)
>   selenium-webdriver
>   spring
>   spring-watcher-listen (~> 2.0.0)
>   tzinfo-data
>   web-console (>= 3.3.0)
>   webpacker (~> 3.5)
> 
> RUBY VERSION
>    ruby 2.5.3p105
> 
> BUNDLED WITH
>    2.1.4
>

**Comment by matheusvetor** [comment]
I think jets runs on top of rack, o you will no need webserver like puma or webrick. Did you follow [this article](https://blog.boltops.com/2018/11/03/jets-mega-mode-run-rails-on-aws-lambda)?

**Comment by hamza-sondermarketing** [comment]
@matheusvetor I have followed this article https://rubyonjets.com/docs/rails/afterburner/ . I have not created jets application but a rails application and added a `.jets` folder like explained in the article.

**Comment by hamza-sondermarketing** [comment]
@matheusvetor Any help here ?

**Comment by tongueroo** [comment]
See #464 Closing out
